#!/bin/bash
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

unset GIT_DIR

cd $OPENSHIFT_REPO_DIR
wget http://getcomposer.org/composer.phar
chmod 755 composer.phar
php composer.phar update
