PhotoTreeSecurityBundle:
    resource: "@PhotoTreeSecurityBundle/Resources/config/routing.yml"
    prefix:   /phototree/

PhotoTreeAlbumBundle:
    resource: "@PhotoTreeAlbumBundle/Resources/config/routing.yml"
    prefix:   /phototree/

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
