PhotoTree\Bundle\AlbumBundle\Domain\Name\Name:
    type: entity
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        firstName:
            type: string
            column: first_name
        lastName:
            type: string
            column: last_name
    oneToOne:
        participant:
            targetEntity: PhotoTree\Bundle\AlbumBundle\Domain\Event\Participant\Participant
            mappedBy: name