parameters:
#    photo_tree_security.example.class: PhotoTree\Bundle\SecurityBundle\Example

services:
#    photo_tree_security.example:
#        class: %photo_tree_security.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
