PhotoTreeAlbumBundle_homepage:
    pattern:  /
    defaults: { _controller: PhotoTreeAlbumBundle:Default:index }

PhotoTreeAlbumBundle_search:
    pattern:  /search
    defaults: { _controller: PhotoTreeAlbumBundle:Search:query }

PhotoTreeAlbumBundle_person:
    pattern:  /person/{id}
    defaults: { _controller: PhotoTreeAlbumBundle:Person:view }
