parameters:
#    photo_tree_album.example.class: PhotoTree\Bundle\AlbumBundle\Example

services:
#    photo_tree_album.example:
#        class: %photo_tree_album.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
